#include "function.hh"

#include <gemmi/elem.hpp>
#include <gemmi/model.hpp>
#include <gemmi/unitcell.hpp>

#include <coot/lidia-core/use-rdkit.hh>

#include <coot/lidia-core/rdkit-interface.hh>
#include <coot/geometry/protein-geometry.hh>

#include "/lmb/home/jdialpuri/Development/coot-tooling/generated-tests/coot__util__get_residue_alt_confs/gemmi/function.hh"
#include "/lmb/home/jdialpuri/Development/coot-tooling/generated-tests/coot__rdkit_mol__fc14ef/gemmi/function.hh"

#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <memory>

using namespace RDKit;

std::pair<bool, std::string>
coot::add_hydrogens_with_rdkit_gemmi(
    gemmi::CRA cra,
    const coot::dictionary_residue_restraints_t &restraints) {

   bool r = false;
   std::string error_message;

   if (cra.residue) {
      const PeriodicTable *tbl = PeriodicTable::getTable();
      try {

         // first save the existing hydrogen names. We don't want to
         // add a hydrogen with the same name as an atom we already
         // have.
         std::vector<std::string> existing_H_names;

         for (const auto &atom : cra.residue->atoms) {
            if (atom.name == " ter") {
               continue;
            }
            if (atom.element.is_hydrogen()) {
               existing_H_names.push_back(atom.name);
            }
         }

         // get out now if there are existing hydrogens,
         // MolOps::addHs() throws an exception if there are hydrogens
         // on the molecule already.
         if (!existing_H_names.empty()) {
            return std::pair<bool, std::string>(false,
                                                "Ligand contains (some) hydrogens already");
         }

         std::vector<std::string> residue_alt_confs =
             coot::util::get_residue_alt_confs_gemmi(*cra.residue);

         for (unsigned int i_alt_conf = 0;
              i_alt_conf < residue_alt_confs.size();
              i_alt_conf++) {

            std::string alt_conf = residue_alt_confs[i_alt_conf];
            RDKit::RWMol m_no_Hs = coot::rdkit_mol_gemmi(
                cra, restraints, residue_alt_confs[i_alt_conf], true);
            unsigned int n_mol_atoms = m_no_Hs.getNumAtoms();

            coot::undelocalise(&m_no_Hs);
            for (unsigned int iat = 0; iat < n_mol_atoms; iat++) {
               RDKit::Atom *at_p = m_no_Hs.getAtomWithIdx(iat);
               at_p->calcImplicitValence(true);
            }

            bool explicit_only = false;
            bool add_coords = true;
            RDKit::ROMol m_no_Hs_ro(m_no_Hs);
            RDKit::ROMol *m_pre =
                RDKit::MolOps::addHs(m_no_Hs_ro, explicit_only, add_coords);
            RDKit::RWMol m(*m_pre);
            delete m_pre;
            unsigned int n_atoms_new = m.getNumAtoms();
            unsigned int n_conf = m.getNumConformers();

            if (!n_conf) {
               std::cout << "ERROR:: mol with Hs: no conformers"
                         << std::endl;
            } else {
               RDKit::Conformer conf = m.getConformer(0);
               std::vector<std::string> H_names_already_added;

               for (unsigned int iat = 0; iat < n_atoms_new; iat++) {
                  RDKit::Atom *at_p = m.getAtomWithIdx(iat);
                  RDGeom::Point3D &r_pos = conf.getAtomPos(iat);
                  std::string name = "";
                  try {
                     at_p->getProp("name", name);

                     // Find atom by name in the gemmi residue
                     gemmi::Atom *res_atom = nullptr;
                     for (auto &a : cra.residue->atoms) {
                        std::string trimmed_name = a.name;
                        trimmed_name.erase(
                            trimmed_name.find_last_not_of(" \t\r\n") + 1);
                        std::string trimmed_query = name;
                        trimmed_query.erase(
                            trimmed_query.find_last_not_of(" \t\r\n") + 1);
                        if (trimmed_name == trimmed_query) {
                           res_atom = &a;
                           break;
                        }
                     }

                     if (res_atom) {
                        std::cout << "setting heavy atom " << name
                                  << " to " << r_pos << std::endl;
                        res_atom->pos.x = r_pos.x;
                        res_atom->pos.y = r_pos.y;
                        res_atom->pos.z = r_pos.z;
                     }

                  } catch (const KeyErrorException &) {

                     // atom is a new one, generated by RDKit.
                     std::string name_i = coot::infer_H_name(
                         iat, at_p, &m, restraints,
                         H_names_already_added);
                     if (!name_i.empty()) {

                        if (std::find(existing_H_names.begin(),
                                      existing_H_names.end(),
                                      name_i) == existing_H_names.end()) {

                           H_names_already_added.push_back(name_i);

                           int n = at_p->getAtomicNum();
                           std::string element = tbl->getElementSymbol(n);

                           gemmi::Atom new_atom;
                           new_atom.name = name_i;
                           new_atom.pos =
                               gemmi::Position(r_pos.x, r_pos.y, r_pos.z);
                           new_atom.occ = 1.0f;
                           new_atom.b_iso = 30.0f;
                           new_atom.element = gemmi::Element(n);
                           if (alt_conf != "") {
                              new_atom.altloc = alt_conf[0];
                           }

                           cra.residue->atoms.push_back(new_atom);
                           r = true;
                        }
                     }
                  }
               }
            }
         }

      } catch (const std::runtime_error &e) {
         std::cout << e.what() << std::endl;
      } catch (const std::exception &rdkit_error) {
         std::cout << rdkit_error.what() << std::endl;
      }
   }
   return std::pair<bool, std::string>(r, error_message);
}
